#!/bin/bash

branch=$(git branch | grep '*' | cut -d ' ' -f 2)

if [ "$branch" = "production/deploy" ]
then
  stage=prod
elif [ "$branch" = "master" ]
then
  stage=staging
elif [[ $branch == feature-* ]]
then
  stage=dev
fi

# use variables from stage files
source stages/$stage

export AWS_DEFAULT_REGION=us-east-1

echo $stage
cd web
make build version=$webversion
make push version=$webversion
make deploy version=$webversion

cd ../api
make build version=$apiversion
make push version=$apiversion
make deploy version=$apiversion
